name: RSYNC Deploy

on:
  push:
    branches:
      - 'never'  # любые ветки, чтобы подхватить Environment по ветке

jobs:
  rsync-deploy:
    runs-on: ubuntu-latest

    # Environment автоматически берём из имени ветки 
    environment: ${{ github.ref_name }}

    env:
      DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
      DEPLOY_USER: ${{ vars.DEPLOY_USER }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
      DEPLOY_LOCAL_DIR: ${{ vars.DEPLOY_LOCAL_DIR || './' }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_MIRROR: ${{ vars.DEPLOY_MIRROR || 'true' }}
      DEPLOY_PORT: ${{ vars.DEPLOY_PORT || '22' }}

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via rsync/SSH
        shell: bash

        run: |
            set -euo pipefail

            if [ -z "${DEPLOY_KEY:-}" ]; then
                echo "::error ::DEPLOY_KEY is not set"
                exit 1
            fi

            echo "$DEPLOY_KEY" > key.pem
            chmod 600 key.pem

            RSYNC_DELETE=""
            if [ "${DEPLOY_MIRROR}" = "true" ]; then
            RSYNC_DELETE="--delete"
            fi

            echo "Deploying repository to $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
            rsync -az --progress $RSYNC_DELETE \
            -e "ssh -i key.pem -o StrictHostKeyChecking=no -p $DEPLOY_PORT" \
            ./ "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"

            rm -f key.pem