name: ci-cd

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}

    env:
      DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
      DEPLOY_USER: ${{ vars.DEPLOY_USER }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
      DEPLOY_LOCAL_DIR: ${{ vars.DEPLOY_LOCAL_DIR || './' }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_MIRROR: ${{ vars.DEPLOY_MIRROR || 'false' }}
      DEPLOY_PORT: ${{ vars.DEPLOY_PORT || '22' }}
      DEPLOY_METHOD: ${{ vars.DEPLOY_METHOD }}
      BUILD_COMMAND: ${{ vars.BUILD_COMMAND }}

    steps:
      - uses: actions/checkout@v4

      - name: BUILD
        if: ${{ env.BUILD_COMMAND != '' }}
        shell: bash
        run: |
          set -euo pipefail

          npm ci
          
          $BUILD_COMMAND
          
      - name: APT CACHE
        if: ${{ env.DEPLOY_METHOD == 'FTP' }}
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: apt-cache-${{ runner.os }}-lftp
          restore-keys: |
            apt-cache-${{ runner.os }}-

      - name: FTP DEPLOY
        if: ${{ env.DEPLOY_METHOD == 'FTP' }}
        shell: bash
        run: |
          set -euo pipefail

          sudo apt-get install -y --no-install-recommends lftp

          DELETE=""
          if [ "${DEPLOY_MIRROR}" = "true" ]; then
            DELETE="--delete"
          fi

          lftp -u "$DEPLOY_USER,$DEPLOY_KEY" "$DEPLOY_HOST" -e "
            mirror -R \
              --parallel=4 \
              --verbose \
              $DELETE \
              -x '(^|/)\.' \
              $DEPLOY_LOCAL_DIR \
              $DEPLOY_PATH ;
            quit
          "

      - name: RSYNC DEPLOY
        if: ${{ env.DEPLOY_METHOD == 'RSYNC' }}
        shell: bash
        run: |
          set -euo pipefail

          DELETE=""
          if [ "${DEPLOY_MIRROR}" = "true" ]; then
            DELETE="--delete"
          fi

          TMP_KEY=$(mktemp)
          echo "$DEPLOY_KEY" > "$TMP_KEY"
          chmod 600 "$TMP_KEY"

          rsync -az --progress $DELETE \
            -e "ssh -i $TMP_KEY -o StrictHostKeyChecking=no -p $DEPLOY_PORT" \
            --exclude='.*' \
            "$DEPLOY_LOCAL_DIR/" "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"

          rm -f "$TMP_KEY"

      - name: GIT DEPLOY
        if: ${{ env.DEPLOY_METHOD == 'GIT' }}
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        shell: bash
        run: |
          set -euo pipefail

          TMP_KEY=$(mktemp)
          echo "$DEPLOY_KEY" > "$TMP_KEY"
          chmod 600 "$TMP_KEY"

          ssh -i $TMP_KEY -o StrictHostKeyChecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "
            cd $DEPLOY_PATH
            if [ ! -d '.git' ]; then
              git clone --branch ${GITHUB_REF_NAME} git@github.com:${GITHUB_REPOSITORY}.git .
            else
              if [ "${DEPLOY_MIRROR}" = "true" ]; then
                git fetch origin ${GITHUB_REF_NAME}
                git reset --hard origin/${GITHUB_REF_NAME}
              else
                git pull origin ${GITHUB_REF_NAME}
              fi
            fi
          "
          
          rm -f "$TMP_KEY"
