name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}

    env:
      DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
      DEPLOY_USER: ${{ vars.DEPLOY_USER }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
      DEPLOY_LOCAL_DIR: ${{ vars.DEPLOY_LOCAL_DIR || './' }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_MIRROR: ${{ vars.DEPLOY_MIRROR || 'true' }}
      DEPLOY_PORT: ${{ vars.DEPLOY_PORT || '22' }}
      DEPLOY_METHOD: ${{ vars.DEPLOY_METHOD || 'NULL' }}

    steps:
      - uses: actions/checkout@v4

      - name: FTP DEPLOY
        if: ${{ env.DEPLOY_METHOD == 'FTP' }}
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y lftp

          DELETE=""
          if [ "${DEPLOY_MIRROR}" = "true" ]; then
            DELETE="--delete"
          fi

          lftp -u "${{ env.DEPLOY_USER }},${{ env.DEPLOY_KEY }}" ${{ env.DEPLOY_HOST }} <<EOF
          mirror -R \
            --parallel=4 \
            --verbose \
            ${DELETE} \
            --exclude-glob .git* \
            ${{ env.DEPLOY_LOCAL_DIR }} \
            ${{ env.DEPLOY_PATH }}
          quit
          EOF

      - name: RSYNC DEPLOY
        if: ${{ env.DEPLOY_METHOD == 'RSYNC' }}
        shell: bash
        run: |
          set -euo pipefail

          echo "$DEPLOY_KEY" > key.pem
          chmod 600 key.pem

          DELETE=""
          if [ "${DEPLOY_MIRROR}" = "true" ]; then
            DELETE="--delete"
          fi

          rsync -az --progress $DELETE \
            -e "ssh -i key.pem -o StrictHostKeyChecking=no -p $DEPLOY_PORT" \
            "$DEPLOY_LOCAL_DIR/" "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"

          rm -f key.pem